---
- name: Install IIS 
  win_feature:
    name: "{{ item }}"
    state: present
    with_items:
      - Web-Server
      - IIS-WebServerRole

- name: start IIS
  win_service:
    name: W3SVC
    state: started
  
